// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ75skd6I1d3OCRoxodWL0FZOq5EF5kNw',
    appId: '1:280644542271:web:dfba636edc8fa488cdfd8a',
    messagingSenderId: '280644542271',
    projectId: 'inventory-app-227cd',
    authDomain: 'inventory-app-227cd.firebaseapp.com',
    storageBucket: 'inventory-app-227cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1hIWfnp6Lw-3h24XQR-OBIBW9SfDEsHQ',
    appId: '1:280644542271:android:6d15621f01f5a7d5cdfd8a',
    messagingSenderId: '280644542271',
    projectId: 'inventory-app-227cd',
    storageBucket: 'inventory-app-227cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh4UrWuBsZ3yUjtmdVr5knM2GwN8aPY-k',
    appId: '1:280644542271:ios:2d28876444cc90eccdfd8a',
    messagingSenderId: '280644542271',
    projectId: 'inventory-app-227cd',
    storageBucket: 'inventory-app-227cd.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh4UrWuBsZ3yUjtmdVr5knM2GwN8aPY-k',
    appId: '1:280644542271:ios:2d28876444cc90eccdfd8a',
    messagingSenderId: '280644542271',
    projectId: 'inventory-app-227cd',
    storageBucket: 'inventory-app-227cd.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ75skd6I1d3OCRoxodWL0FZOq5EF5kNw',
    appId: '1:280644542271:web:2cae2dd38a12d799cdfd8a',
    messagingSenderId: '280644542271',
    projectId: 'inventory-app-227cd',
    authDomain: 'inventory-app-227cd.firebaseapp.com',
    storageBucket: 'inventory-app-227cd.firebasestorage.app',
  );
}
